api:
    security:
        secret: ${JWT_SECRET:123456}
spring:
    data:
        web:
            pageable:
                page-parameter: pagina
                size-parameter: size
            sort:
                sort-parameter: orden
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost/vollmedapi
        username: root
        password: 12345678
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
server:
    error:
        include-stacktrace: never
        include-message: never